# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Vita' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'

  # Pods for Vita

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  target 'VitaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Vita-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Vita-tvOS

  target 'Vita-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
